### ISSUE TITLE
Parameter '@MethodConst1' has already been defined.

### ISSUE THREAD

**Issue by netstart188** [sunkaixuan/SqlSugar#117]
at SqlSugar.AdoProvider.GetDataReader(String sql, SugarParameter[] parameters)
   at SqlSugar.QueryableProvider`1.GetData[TResult](KeyValuePair`2 sqlObj)
   at SqlSugar.QueryableProvider`1._ToList[TResult]()
   at SqlSugar.QueryableProvider`1.ToList()
   at SqlSugar.QueryableProvider`1.ToPageList(Int32 pageIndex, Int32 pageSize)
   at SqlSugar.QueryableProvider`1.<>c__DisplayClass101_0.<ToPageList>b__0()
   at SqlSugar.UtilMethods.GetOldValue[T](T value, Action action)
   at SqlSugar.QueryableProvider`1.ToPageList(Int32 pageIndex, Int32 pageSize, Int32& totalNumber)
   at SqlSugar.QueryableProvider`1.<>c__DisplayClass130_0.<ToPageListAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---

**Comment by sunkaixuan** [comment]
代码怎么写的

**Comment by netstart188** [comment]
var entities = await _dbRepository.Queryable<RoomUser>().Where(u =>
            (u.CommunityID == communityId || SqlFunc.IsNullOrEmpty(communityId)) &&
            (SqlFunc.Contains(u.BuildID, buildId) || SqlFunc.IsNullOrEmpty(buildId)) &&
            (SqlFunc.Contains(u.UnitID, unitId) || SqlFunc.IsNullOrEmpty(unitId)) &&
            (SqlFunc.Contains(u.RoomNumber, keyword) || SqlFunc.Contains(u.RoomerName, keyword) ||
                     SqlFunc.Contains(u.HousePlace, keyword) || SqlFunc.Contains(u.UnitName, keyword) ||
                     SqlFunc.Contains(u.BuildName, keyword) || SqlFunc.IsNullOrEmpty(keyword)))
             .GroupBy(ru => new { ru.RoomNumber, ru.RoomID }).Select(ru => new
             {
                 RoomNumber = SqlFunc.AggregateMax(ru.RoomNumber),
                 CountRoomer = SqlFunc.AggregateCount(ru.RoomerName),
                 RoomID = SqlFunc.AggregateMax(ru.RoomID),
                 Owner = SqlFunc.Subqueryable<RoomUser>().Where(r => r.RoomID == ru.RoomID && SqlFunc.Equals(r.RoomUserType, "业主")).Select(s => s.RoomerName)
             }).OrderBy((r) => r.RoomNumber, type: OrderByType.Desc).ToPageListAsync(pageIndex, pageSize);

**Comment by sunkaixuan** [comment]
已修改
