### ISSUE TITLE
Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by MrAnderson1989** [sunkaixuan/SqlSugar#486]
下面是我使用的语句：
 var result = await Db.Queryable<Entity>()
                                .Where(s => s.ParentFileID == FileID && s.FileExtension.ToLower() == fileEx)
                                .OrderBy(s => s.CreateTime, SqlSugar.OrderByType.Desc)
                                .FirstAsync();

当应用程序第一次被访问时会报这个错误，再次刷新问题就不见了

报错信息：
Collection was modified; enumeration operation may not execute.

推测是foreach时对数据进行了修改，导致此问题。

部分调用堆栈：
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at SqlSugar.EntityMaintenance.SetColumns(EntityInfo result)
   at SqlSugar.EntityMaintenance.<>c__DisplayClass5_0.<GetEntityInfo>b__0()
   at SqlSugar.ReflectionInoCore`1.GetOrCreate(String cacheKey, Func`1 create)
   at SqlSugar.ReflectionInoCacheService.GetOrCreate[V](String cacheKey, Func`1 create, Int32 cacheDurationInSeconds)
   at SqlSugar.EntityMaintenance.GetEntityInfo(Type type)
   at SqlSugar.SqlSugarClient.<>c__DisplayClass55_0.<InitMppingInfo>b__0()
   at SqlSugar.ReflectionInoCore`1.GetOrCreate(String cacheKey, Func`1 create)
   at SqlSugar.ReflectionInoCacheService.GetOrCreate[V](String cacheKey, Func`1 create, Int32 cacheDurationInSeconds)
   at SqlSugar.SqlSugarClient.InitMppingInfo(Type type)
   at SqlSugar.SqlSugarClient.InitMppingInfo[T]()
   at SqlSugar.SqlSugarClient.Queryable[T]()

**Comment by zhan520g** [comment]
有可能是别的服务对这个表做了操作
