### ISSUE TITLE
异步方法经常概率性产生异常:阅读器关闭时尝试调用 FieldCount 无效。”

### ISSUE THREAD

**Issue by gxrsprite** [sunkaixuan/SqlSugar#511]
System.InvalidOperationException:“阅读器关闭时尝试调用 FieldCount 无效。”

   at System.Data.SqlClient.SqlDataReader.get_FieldCount()
   at SqlSugar.DbBindAccessory.GetDataReaderNames(IDataReader dataReader)
   at SqlSugar.DbBindAccessory.<GetEntityListAsync>d__1`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SqlSugar.DbBindProvider.<DataReaderToListAsync>d__11`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SqlSugar.QueryableProvider`1.<GetDataAsync>d__191`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SqlSugar.QueryableProvider`1.<GetDataAsync>d__189`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SqlSugar.QueryableProvider`1.<_ToListAsync>d__181`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at

**Comment by gxrsprite** [comment]
阅读器关闭时尝试调用 Read无效

**Comment by sunkaixuan** [comment]
定个可以重现的例子给我
