### ISSUE TITLE
SqlSugar 部分功能用到Newtonsoft.Json.dll，需要在Nuget上安装 Newtonsoft.Json 9.0.0.1及以上版本。如果有版本兼容问题请先删除原有引用（注意：所有项目类库）,全部重新从NUGET下载

### ISSUE THREAD

**Issue by jingyulong** [sunkaixuan/SqlSugar#517]
,如果还不明白，请查看详细教程 http://www.codeisbug.com/Doc/8/1154'

这篇教程我看了，不是很明白为什么我通过Nuget安装的Newtonsoft,Json版本不行。

我是调用此段代码：
```
        //调式代码 用来打印SQL 
        Db.Aop.OnLogExecuting = (sql, pars) =>
        {            
            Console.WriteLine(sql + "\r\n" +
                Db.Utilities.SerializeObject(pars.ToDictionary(it => it.ParameterName, it => it.Value)));
            Console.WriteLine();
        };
```

出现报错：
```Chinese Message :  SqlSugar 部分功能用到Newtonsoft.Json.dll，需要在Nuget上安装 Newtonsoft.Json 9.0.0.1及以上版本。如果有版本兼容问题请先删除原有引用（注意：所有项目类库）,全部重新从NUGET下载,如果还不明白，请查看详细教程 http://www.codeisbug.com/Doc/8/1154'
```

堆栈：
```
   at SqlSugar.DependencyManagement.TryJsonNet()
   at SqlSugar.ContextMethods.SerializeObject(Object value)
   at DbContext`1.<.ctor>b__0_0(String sql, SugarParameter[] pars) in BusinessCore\DbCore\DbContext.cs:line 27
   at SqlSugar.AdoProvider.ExecuteBefore(String sql, SugarParameter[] parameters)
   at SqlSugar.AdoProvider.GetDataReader(String sql, SugarParameter[] parameters)
```

Newtonsoft.Json DLL引用路径：
```    <Reference Include="Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed, processorArchitecture=MSIL">
      <HintPath>..\packages\Newtonsoft.Json.12.0.2\lib\net45\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="SqlSugar, Version=5.0.0.9, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\packages\sqlSugar.5.0.0.9\lib\SqlSugar.dll</HintPath>
```
Newtonsoft.Json版本：12.0.2
SqlSugar版本：5.0.0.9

都是通过Nuget安装的，使用

Update-Package   | Update-Package -reinstall    全部重新安装过

appconfig:
```
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-12.0.0.0" newVersion="12.0.0.0" />
      </dependentAssembly>
```

能帮忙看看是什么问题吗？

**Comment by jingyulong** [comment]
> 新建 个控制台你试一下一定好的，可能是老项目的问题

今天很奇迹般的好了，谢谢你~ @sunkaixuan

**Comment by Pipe-shen** [comment]
> > 新建 个控制台你试一下一定好的，可能是老项目的问题
> 
> 今天很奇迹般的好了，谢谢你~ @sunkaixuan

奇迹般的好了，是怎么好的，我也遇到这个问题了 /哭

**Comment by jingyulong** [comment]
> > > 新建 个控制台你试一下一定好的，可能是老项目的问题
> > 
> > 
> > 今天很奇迹般的好了，谢谢你~ @sunkaixuan
> 
> 奇迹般的好了，是怎么好的，我也遇到这个问题了 /哭

我也忘记了，当时应该记下来的。。。。你重新建一个项目试试

**Comment by zsnivy** [comment]
> 奇迹般的好了，是怎么好的，我也遇到这个问题了 /哭

可能是官方给的代码中
``` CSharp
//用来打印Sql方便你调式    
db.Aop.OnLogExecuting = (sql, pars) =>
            {
                Console.WriteLine(sql + "\r\n" + 
                db.Utilities.SerializeObject(pars.ToDictionary(it => it.ParameterName, it => it.Value)));
                Console.WriteLine();
            };
```
 `db.Utilities.SerializeObject(object)` 这个方法里面会调用 `DependencyManagement.TryJsonNet(object)` ，往里会直接调用Newtonsoft.Json的 `JsonConvert.SerializeObject(object)` 。而源码中SqlSugar项目是直接引用的 9.0 的dll文件，所以你的项目里也要指定版本的dll才可以正常运行。
我个人的解决方法，有问题可以继续讨论：
1. 上面aop的debug代码用自己的而不用官方给的，即可避免调用到 `DependencyManagement.TryJsonNet(object)` 方法；
2. 下载SqlSugar源码，Nuget卸载SqlSugar，引用源码项目，改源码的引用为你自己的Newtonsoft.Json.dll（与你项目的Newtonsoft版本一致即可）
