### ISSUE TITLE
异步ToPageListAsync经常：Invalid operation. The connection is closed.

### ISSUE THREAD

**Issue by cnkker** [sunkaixuan/SqlSugar#669]
[16:42:15 ERR] 查询异常
System.InvalidOperationException: Invalid operation. The connection is closed.
   at SqlSugar.AdoProvider.GetDataReaderAsync(String sql, SugarParameter[] parameters)
   at SqlSugar.QueryableProvider`1.GetDataAsync[TResult](KeyValuePair`2 sqlObj)
   at SqlSugar.QueryableProvider`1._ToListAsync[TResult]()
   at SqlSugar.QueryableProvider`1.ToPageListAsync(Int32 pageIndex, Int32 pageSize, RefAsync`1 totalNumber)
   at YunMa.Dormitory.Repository.Evaluation.StudentAppraisalRepository.<>c__DisplayClass4_0.<<GetPager>b__0>d.MoveNext() in D:\work\code\DigitalCampus\ProjectCode\Dormitory\YunMa.Dormitory.Repository\Evaluation\StudentAppraisalRepository.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
………………………………
错误异常如上！

**Comment by sunkaixuan** [comment]
DB不能单例

**Comment by cnkker** [comment]
DB不能单例，对事务有影响吗？
