### ISSUE TITLE
使用MyCat多节点时 MySql.Data报错

### ISSUE THREAD

**Issue by SunyaoMeng** [sunkaixuan/SqlSugar#735]
错误信息：
The given key was not present in the dictionary.
at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at MySql.Data.MySqlClient.MySqlField.SetFieldEncoding()
   at MySql.Data.MySqlClient.NativeDriver.GetColumnData(MySqlField field)
   at MySql.Data.MySqlClient.NativeDriver.GetColumnsData(MySqlField[] columns)
   at MySql.Data.MySqlClient.Driver.GetColumns(Int32 count)
   at MySql.Data.MySqlClient.ResultSet.LoadColumns(Int32 numCols)
   at MySql.Data.MySqlClient.ResultSet..ctor(Driver d, Int32 statementId, Int32 numCols)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlDataReader.Close()
   at MySql.Data.MySqlClient.MySqlCommand.ResetReader()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
更换成MySqlConnector可解决

**Comment by sunkaixuan** [comment]
var myconn=(db.adoconnection as mysqlconnection)

**Comment by SunyaoMeng** [comment]
> var myconn=(db.adoconnection as mysqlconnection)

上面是MySql.Data的底层错误，在非使用Sqlsugar的情况下依旧出现，用MySqlConnector的确不再出现上述错误，但是自己魔改时发现，MySqlConnector的Conn.Close需要配合 ClearPool才能真实关闭。当前处理方式是，不使用自动回收，等待运行完后手动回收。
