### ISSUE TITLE
Collection was modified; enumeration operation may not execute

### ISSUE THREAD

**Issue by OceansMaster** [sunkaixuan/SqlSugar#809]
我在使用update时，是处于 parallel.foreach 下并行运行的，  非常罕见的会报下述错误

System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at SqlSugar.SqlSugarProvider.InitMappingInfo(EntityInfo entityInfo)
   at SqlSugar.SqlSugarProvider.InitMappingInfo(Type type)
   at SqlSugar.SqlSugarProvider.InitMappingInfo[T]()
   at SqlSugar.SqlSugarProvider.Updateable[T](T[] UpdateObjs)
   at SqlSugar.SqlSugarProvider.Updateable[T](T UpdateObj)
   at SqlSugar.SqlSugarClient.Updateable[T](T UpdateObj)

报错的并行执行的代码块中使用同一个SqlSugarClient实例；但不排除进程中有其他代码块会构造新的SqlSugarClient实例，并在并发下运行..  是否SqlSugarProvider中的MappingColumns、IgnoreColumns 这些List在 InitMappingInfo(EntityInfo entityInfo）方法执行时存在线性安全问题？  但如果时并发的线性安全问题，理论上应该很容易复现，但该问题目前非常难复现，并只在位置有出现..  我使用的版本是5.0.0.15

**Comment by sunkaixuan** [comment]
http://www.codeisbug.com/Home/Doc?typeId=1213 统一提交入口
