### ISSUE TITLE
进行Update操作时使用日志功能出现NRE问题

### ISSUE THREAD

**Issue by tiger5331819** [sunkaixuan/SqlSugar#827]
System.NullReferenceException: Object reference not set to an instance of an object.
         at SqlSugar.UpdateableProvider`1.<>c__DisplayClass133_0.<GetDiffTable>b__0(EntityColumnInfo it)
         at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
         at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
         at SqlSugar.UpdateableProvider`1.GetDiffTable(String sql, List`1 parameters)
         at SqlSugar.UpdateableProvider`1.Before(String sql)
         at SqlSugar.UpdateableProvider`1._ExecuteCommand()
         at SqlSugar.UpdateableProvider`1.ExecuteCommand()

`var update = _db.Updateable(entity).UpdateColumnsIF(updateColumns != null, updateColumns);`
`if (whereExp != null)`
       `update = update.Where(whereExp);`
`return update.EnableDiffLogEvent().ExecuteCommand();`

**Comment by sunkaixuan** [comment]
请把你的逻辑去掉给出能重现的步骤

**Comment by sunkaixuan** [comment]
http://www.codeisbug.com/Home/Doc?typeId=1213 统一提交入口
